utils/force-app/main/default/serviceBase/objects/Service_Invocation__mdt/fields/Async_Platform_Event__c.field-meta.xml
<CustomField>
    <fullName>Async_Platform_Event__c</fullName>
    <label>Async Platform Event</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

utils/force-app/main/default/serviceBase/objects/Service_Invocation__mdt/fields/Enforce_Stub__c.field-meta.xml
<CustomField>
    <fullName>Enforce_Stub__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked then the Stub Class is used by the service regardless of any other context logic.</description>
    <inlineHelpText>If checked then the Stub Class is used by the service regardless of any other context logic.</inlineHelpText>
    <label>Enforce Stub</label>
    <type>Checkbox</type>
</CustomField>

utils/force-app/main/default/serviceBase/objects/Service_Invocation__mdt/fields/Expect_Response__c.field-meta.xml
<CustomField>
    <fullName>Expect_Response__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checked if the service invocation expects a response</description>
    <inlineHelpText>Checked if the service invocation expects a response</inlineHelpText>
    <label>Expect Response</label>
    <type>Checkbox</type>
</CustomField>

utils/force-app/main/default/serviceBase/objects/Service_Invocation__mdt/fields/Invocation_Type__c.field-meta.xml
<CustomField>
    <fullName>Invocation_Type__c</fullName>
    <defaultValue>&quot;Sync&quot;</defaultValue>
    <label>Invocation Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sync</fullName>
                <default>true</default>
                <label>Sync</label>
            </value>
            <value>
                <fullName>Async</fullName>
            </value>
            <value>
                <fullName>Stub</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

utils/force-app/main/default/serviceBase/objects/Service_Invocation__mdt/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <label>Service</label>
    <referenceTo>Service__mdt</referenceTo>
    <relationshipLabel>Service Invocations</relationshipLabel>
    <relationshipName>Service_Invocations</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

utils/force-app/main/default/serviceBase/objects/Service_Invocation__mdt/fields/Service_Version__c.field-meta.xml
<CustomField>
    <fullName>Service_Version__c</fullName>
    <label>Service Version</label>
    <referenceTo>Service_Version__mdt</referenceTo>
    <relationshipLabel>Service Invocations</relationshipLabel>
    <relationshipName>Service_Invocations</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

utils/force-app/main/default/serviceBase/objects/Service_Invocation__mdt/fields/Stub_Class__c.field-meta.xml
<CustomField>
    <fullName>Stub_Class__c</fullName>
    <description>In development phases we may want to call a stub class for a service invocation. In this case we configure the Service Type to be stub and we create a Callable class to implement that stub and put its name as the Stub class.</description>
    <inlineHelpText>In development phases we may want to call a stub class for a service invocation. In this case we configure the Service Type to be stub and we create a Callable class to implement that stub and put its name as the Stub class.</inlineHelpText>
    <label>Stub Class</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

utils/force-app/main/default/serviceBase/objects/Service_Version__mdt/Service_Version__mdt.object-meta.xml
<CustomObject>
    <label>Service Version</label>
    <pluralLabel>Service Versions</pluralLabel>
</CustomObject>

utils/force-app/main/default/serviceBase/objects/Service_Version__mdt/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <label>Service</label>
    <referenceTo>Service__mdt</referenceTo>
    <relationshipLabel>Service Versions</relationshipLabel>
    <relationshipName>Service_Versions</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

utils/force-app/main/default/serviceBase/objects/Service_Version__mdt/fields/Service_Version_Number__c.field-meta.xml
<CustomField>
    <fullName>Service_Version_Number__c</fullName>
    <label>Service Version Number</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

utils/force-app/main/default/serviceBase/classes/ServiceInvocation.cls
public inherited sharing class ServiceInvocation {

    String serviceInvocationName;
    Service_Invocation__mdt meta;

    public ServiceInvocation(String serviceInvocationName) {
        this.serviceInvocationName = serviceInvocationName;
    }

    public Service_Invocation__mdt retrieveMetadata () {
        meta = CMT.getServiceInvocationByDeveloperName (this.serviceInvocationName);
        return meta;
    }

    public Service_Invocation__mdt getMeta () {
        return this.meta;
    }

    /* This is a generic class and should move */
    public static Callable getStubClass (String className) {
        return (Callable) Type.forName(className).newInstance();
    }

    public boolean getExpectResponse () {
        return meta.Expect_Response__c;
    }

    // A generic Service Invocation Method. 

    public Object invoke(IService_Input_Master isim) {
        return this.invoke(isim.getArgs());
    }

    private Object invoke(Map<String,Object> args) {

        IService_Output_Master isom = null;

        retrieveMetadata();

        Service.ActionDefinition sad = new Service.ActionDefinition();
        sad.serviceName = meta.Service__r.DeveloperName;
        sad.serviceVersion = (Integer) meta.Service_Version__r.Service_Version_Number__c;
        sad.invocationType = meta.Invocation_Type__c;
        sad.userId = UserInfo.getUserId();
        sad.logRequests = meta.Log_Requests__c;
        sad.ServiceInvocationName = meta.DeveloperName;
        sad.stubClass = meta.Stub_Class__c;
        sad.expectResponse = meta.Expect_Response__c;
        sad.asyncPlatformEvent = meta.Async_Platform_Event__c;
        sad.enforceStub = meta.Enforce_Stub__c;

        // TODO Need to apply any invocation overrides here.

        String strActionDefinition = sad.serialize();

        System.debug('Invocation_Type__c invoked:' + meta.Invocation_Type__c);

        switch on meta.Invocation_Type__c {
            when 'Sync' , 'Stub' {
                Service service = new Service();
                if (meta.Expect_Response__c) {
                    isom = (IService_Output_Master) service.call(strActionDefinition, args);
                }
                else {
                    service.call(strActionDefinition, args);
                }
            }
            when 'Async' {
                System.debug('Async invoked');
                Schema.SObjectType targetType = Schema.getGlobalDescribe().get(meta.Async_Platform_Event__c);
                SObject sobj = targetType.newSObject();
                sobj.put('Action__c', strActionDefinition);
                sobj.put('Args__c', JSON.serialize(args));
                EventBus.publish(sobj);
            }
        }

        return isom;

    }




}