utils/force-app/main/default/serviceBase/objects/Service_Invocation__mdt/fields/Async_Platform_Event__c.field-meta.xml
<CustomField>
    <fullName>Async_Platform_Event__c</fullName>
    <label>Async Platform Event</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

utils/force-app/main/default/serviceBase/objects/Service_Invocation__mdt/fields/Enforce_Stub__c.field-meta.xml
<CustomField>
    <fullName>Enforce_Stub__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked then the Stub Class is used by the service regardless of any other context logic.</description>
    <inlineHelpText>If checked then the Stub Class is used by the service regardless of any other context logic.</inlineHelpText>
    <label>Enforce Stub</label>
    <type>Checkbox</type>
</CustomField>

utils/force-app/main/default/serviceBase/objects/Service_Invocation__mdt/fields/Expect_Response__c.field-meta.xml
<CustomField>
    <fullName>Expect_Response__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checked if the service invocation expects a response</description>
    <inlineHelpText>Checked if the service invocation expects a response</inlineHelpText>
    <label>Expect Response</label>
    <type>Checkbox</type>
</CustomField>

utils/force-app/main/default/serviceBase/objects/Service_Invocation__mdt/fields/Invocation_Type__c.field-meta.xml
<CustomField>
    <fullName>Invocation_Type__c</fullName>
    <defaultValue>&quot;Sync&quot;</defaultValue>
    <label>Invocation Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sync</fullName>
                <default>true</default>
                <label>Sync</label>
            </value>
            <value>
                <fullName>Async</fullName>
            </value>
            <value>
                <fullName>Stub</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

utils/force-app/main/default/serviceBase/objects/Service_Invocation__mdt/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <label>Service</label>
    <referenceTo>Service__mdt</referenceTo>
    <relationshipLabel>Service Invocations</relationshipLabel>
    <relationshipName>Service_Invocations</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

utils/force-app/main/default/serviceBase/objects/Service_Invocation__mdt/fields/Service_Version__c.field-meta.xml
<CustomField>
    <fullName>Service_Version__c</fullName>
    <label>Service Version</label>
    <referenceTo>Service_Version__mdt</referenceTo>
    <relationshipLabel>Service Invocations</relationshipLabel>
    <relationshipName>Service_Invocations</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

utils/force-app/main/default/serviceBase/objects/Service_Invocation__mdt/fields/Stub_Class__c.field-meta.xml
<CustomField>
    <fullName>Stub_Class__c</fullName>
    <description>In development phases we may want to call a stub class for a service invocation. In this case we configure the Service Type to be stub and we create a Callable class to implement that stub and put its name as the Stub class.</description>
    <inlineHelpText>In development phases we may want to call a stub class for a service invocation. In this case we configure the Service Type to be stub and we create a Callable class to implement that stub and put its name as the Stub class.</inlineHelpText>
    <label>Stub Class</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

utils/force-app/main/default/serviceBase/objects/Service_Version__mdt/Service_Version__mdt.object-meta.xml
<CustomObject>
    <label>Service Version</label>
    <pluralLabel>Service Versions</pluralLabel>
</CustomObject>

utils/force-app/main/default/serviceBase/objects/Service_Version__mdt/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <label>Service</label>
    <referenceTo>Service__mdt</referenceTo>
    <relationshipLabel>Service Versions</relationshipLabel>
    <relationshipName>Service_Versions</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

utils/force-app/main/default/serviceBase/objects/Service_Version__mdt/fields/Service_Version_Number__c.field-meta.xml
<CustomField>
    <fullName>Service_Version_Number__c</fullName>
    <label>Service Version Number</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

utils/force-app/main/default/serviceBase/classes/CMT.cls
public inherited sharing class CMT {
    public CMT() {

    }

    public static Service__mdt getServiceByDeveloperName (String serviceName) {
        List<Service__mdt> listServiceMDT = 
            [SELECT Id, DeveloperName,MasterLabel,Extensible__c, Private__c 
                from Service__mdt
                where DeveloperName = :serviceName];
        
        if (listServiceMDT.size() > 0) {
            return listServiceMDT[0];
        }
        else {
            if (Test.isRunningTest()) {
                // instantiate a CMT and return (cannot save it). 
                // Add additional attributes in the calling method.
                Service__mdt serviceMDT = new Service__mdt();
                serviceMDT.DeveloperName = serviceName;
                return serviceMDT;
            }            
        }
        return null;
    }

    public static Service_Invocation__mdt getServiceInvocationByDeveloperName (String serviceInvocationName) {
        List<Service_Invocation__mdt> listServiceInvocationMDT = 
            [SELECT Id, 
                DeveloperName,
                MasterLabel,
                Invocation_Type__c, 
                Log_Requests__c, 
                Service__c, 
                Stub_Class__c,
                Enforce_Stub__c,
                Async_Platform_Event__c,
                Service_Version__c,
                Expect_Response__c,
                Service__r.DeveloperName ,
                Service_Version__r.Service_Version_Number__c 
                from Service_Invocation__mdt
                where DeveloperName = :serviceInvocationName];
        
        if (listServiceInvocationMDT.size() > 0) {
            return listServiceInvocationMDT[0];
        }
        else {
            if (Test.isRunningTest()) {
                // instantiate a CMT and return (cannot save it). 
                // Add additional attributes in the calling method.
                Service_Invocation__mdt serviceInvocationMDT = new Service_Invocation__mdt();
                serviceInvocationMDT.DeveloperName = serviceInvocationName;
                return serviceInvocationMDT;
            }            
        }
        return null;
    }



}